database: h2
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  profiles:
    active: local
    include:
  session:
    store-type: jdbc
  datasource:
    platform: h2
    data: classpath*:db/${database}/data.sql
    url: jdbc:h2:tcp://localhost/~/guhaedog
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    database-platform: H2
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

