database: h2
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  profiles:
    active: local
    include: real-oauth
  session:
    store-type: jdbc
  datasource:
    platform: h2
    data: classpath*:db/${database}/data.sql
    url: jdbc:h2:tcp://localhost/~/guhaedog
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

#database: mysql
#spring:
#  profiles:
#    active: local
#    include: real-oauth
#  datasource:
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    data: classpath*:db/${database}/data.sql
#    initialization-mode: always
#    url: jdbc:mysql://localhost:3306/Guhaedog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    generate-ddl: true
#
#    hibernate:
#      ddl-auto: create
#
#
#
